project:
  type: website
  output-dir: docs

website:
  title: "Thermal Power Plant Simulator"
  description: "Fall 2027 - Official Course Website"
  navbar:
    background: primary
    pinned: true   # ← this makes it sticky
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: resources.qmd
        text: Resources
      - href: references.qmd
        text: References
      # - href: about.qmd
      #   text: About
    # right:
    #   - icon: github
    #     href: https://github.com/volumen25/thermal-power-plant-simulator
  back-to-top-navigation: true
  page-footer:
    left: © 2026 <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
    right: |
      Built with <a href="https://quarto.org">Quarto {{< version >}}</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false
    smooth-scroll: true

bibliography: references.bib
csl: apa.csl

execute:
  freeze: auto